spring.application.name=proyecto-software

########## CONEXION BASE DE DATOS #########
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=5

########## JWT #########
app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=${JWT_ISSUER:tickethub}
app.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:3600000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}
app.jwt.verify-email-expiration-ms=${JWT_VERIFY_EMAIL_EXPIRATION_MS:86400000}
app.jwt.reset-password-expiration-ms=${JWT_RESET_PASSWORD_EXPIRATION_MS:1800000}

########## BREVO #########
brevo.api-key=${BREVO_API_KEY}
brevo.api-url=${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME:Proyecto Tickets}

########## FRONTEND #########
app.frontend.url=${FRONTEND_URL}

########## SEGURIDAD #########
app.security.max-intentos-fallidos=${MAX_INTENTOS_FALLIDOS:5}
app.security.bloqueo-minutos=${BLOQUEO_MINUTOS:15}